filepath: examples/bvh/hurray.bvh
start_frame_idx: 0
end_frame_idx: 111
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.005
up: +y