filepath: examples/bvh/cmu1/tictoc1.bvh
start_frame_idx: 0
end_frame_idx: 569
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.005
up: +y
