filepath: examples/bvh/walkk.bvh
start_frame_idx: 0
end_frame_idx: 250
groundplane_joint: RightFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +y
