scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char1/char_cfg.yaml
      motion_cfg: examples/config/motion/runningjump.yaml
      retarget_cfg: examples/config/retarget/mixamo_fff.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./test.gif
view:
  USE_MESA: True