scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/dino/char_cfg.yaml
      motion_cfg: examples/config/motion/lala.yaml
      retarget_cfg: examples/config/retarget/cmu1_pfp_copy.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./.examples/lala.gif
view:
  USE_MESA: True