scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char1/char_cfg.yaml
      motion_cfg: examples/config/motion/runningjump.yaml
      retarget_cfg: examples/config/retarget/mixamo_fff.yaml
view:
  CAMERA_POS: [2.0, 0.7, 8.0]
  CAMERA_FWD: [0.0, 0.5, 8.0]
  USE_MESA: True
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./runningjump.mp4
  OUTPUT_VIDEO_CODEC: avc1