scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/dino/char_cfg.yaml
      motion_cfg: examples/config/motion/wave_hello.yaml
      retarget_cfg: examples/config/retarget/fair1_ppf.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./.examples/wave_hello.gif
view:
  USE_MESA: True